### Variables
@port=8000
@baseUrl = http://localhost:{{port}}

### GET root
GET {{baseUrl}} HTTP/1.1


### GET users
GET {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{authToken}}

### POST users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "leonardo1@test.com",
  "password": "passleo123"
}

### PUT - update user password
PUT {{baseUrl}}/users/249
Content-Type: application/json

{
  "password": "leopass123"
}


### POST login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "leonardo1@test.com",
  "password": "passleo123"
}

###
@authToken = {{login.response.body.token}}


### GET me
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}