### Variables
@port=8000
@baseUrl = http://localhost:{{port}}

### GET root
GET {{baseUrl}} HTTP/1.1


### GET users
GET {{baseUrl}}/users HTTP/1.1

### POST users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "leonardo1@test.com",
  "password": "passleo123"
}